Plan.create!(:title => "tester", :description => "Beta testing TimeTracker!", :value => 0, :duration => "MONTHLY", :project_count => 10, :user_count => 10)
# Plan.create!(:title => "free", :description => "Try out TimeTracker!", :value => 0, :duration => "MONTHLY", :project_count => 1, :user_count => 1)
Plan.create!(:title => "starter", :description => "Great for individuals", :value => 8, :duration => "MONTHLY", :project_count => 2, :user_count => 2)
Plan.create!(:title => "basic", :description => "Good for small organisations", :value => 16, :duration => "MONTHLY", :project_count => 10, :user_count => 15)
Plan.create!(:title => "professional", :description => "Perfect for large organisations", :value => 32, :duration => "MONTHLY", :project_count => 30, :user_count => 100)