company = Company.create(:name => "TerraCoding", :registration_number => "1001")
user_1 = User.create(:company => company, :owns_company => true, :company_admin => true, :email => "domness@gmail.com", :firstname => "Dominic", :lastname => "Wroblewski", :password => "password", :password_confirmation => "password")
user_2 = User.create(:company => company, :owns_company => true, :email => "haargoth@gmail.com", :firstname => "Robert", :lastname => "White", :password => "password", :password_confirmation => "password")
project = Project.create(:company => company, :status => "Active", :name => "TimeTracker")
project_2 = Project.create(:company => company, :status => "Active", :name => "OMS")
project_user = ProjectUser.create(:project => project, :user => user_1)
task_1 = Task.create(:project => project, :name => "Test Task 1", :billable => true, :rate => 20)
task_2 = Task.create(:project => project, :name => "Test Task 2", :billable => false, :rate => 20)
task_3 = Task.create(:project => project, :name => "Test Task 3", :billable => false, :rate => 0)
task_4 = Task.create(:project => project_2, :name => "Test Task 4", :billable => true, :rate => 20)